version: '3.8'

services:
  backend:
    image: nousscda053/bobapp-back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - bobapp-network

  frontend:
    image: nousscda053/bobapp-front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - bobapp-network

networks:
  bobapp-network:
    driver: bridge
