name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build backend Docker image
        run: |
          docker build -t bobapp-back
          docker push bobapp-back:latest

      - name: Build frontend Docker image
        run: |
          docker build -t bobapp-front
          docker push bobapp-front:latest

      - name: Deploy to your server
        run: |
          ssh your_server_user@your_server_ip "docker pull your_dockerhub_username/backend:latest && docker pull your_dockerhub_username/frontend:latest && docker-compose -f your_docker_compose_file.yml up -d"
