name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build backend
      run: mvn -B package --file back/pom.xml

    - name: Run backend tests and generate coverage report
      run: mvn test jacoco:report --file back/pom.xml

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install frontend dependencies
      run: npm install
      working-directory: front

    - name: Build frontend
      run: npm run build --prod
      working-directory: front

    - name: Build and push Docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker build -t $DOCKER_USERNAME/bobapp-back:latest back/
        docker build -t $DOCKER_USERNAME/bobapp-front:latest front/
        docker push $DOCKER_USERNAME/bobapp-back:latest
        docker push $DOCKER_USERNAME/bobapp-front:latest

    - name: Deploy Backend
      run: |
        docker pull $DOCKER_USERNAME/bobapp-back
        docker run -d -p 8080:8080 $DOCKER_USERNAME/bobapp-back

    - name: Deploy Frontend
      run: |
        docker pull $DOCKER_USERNAME/bobapp-front
        docker run -d -p 4200:4200 $DOCKER_USERNAME/bobapp-front
