name: Angular Tests with Coverage

on:
  push:
    branches: [ main ] # Déclenche l'action sur le push vers la branche main
  pull_request:
    branches: [ main ] # Déclenche l'action sur les pull requests vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Récupère le code du dépôt

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Navigate to front directory
      run: cd front

    - name: Install dependencies
      run: npm install
      working-directory: ./front

    - name: Run tests with Karma and generate coverage
      run: npm run test -- --no-watch --code-coverage
      working-directory: ./front

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: front/coverage/
